[pytest]
# Default arguments for multi-browser and tracing
addopts = --browser chromium --browser firefox --browser webkit --screenshot on --video on --tracing retain-on-failure
pythonpath = code
testpaths = code/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Logging configuration
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S
